import { useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'campaign-copy-manager-campaigns'
const COPY_TYPES = [['invitation', 'Invitation'], ['brief', 'Influencer Brief'], ['reminder', 'Reminder'], ['notification', 'App Notification']]
const LOCATION_TYPES = ['Visit', 'Event', 'Store Visit']
const DIALECTS = ['Kuwaiti', 'Saudi', 'Emirati', 'Qatari', 'Omani', 'Bahraini']
const TONES = ['Friendly & Casual', 'Classy & Premium', 'Fun & Energetic', 'Warm & Personal', 'Professional & Polished']
const AUDIENCES = ['Neutral', 'Female', 'Male']
const emptyForm = { id: null, name: '', brand: '', type: 'Delivery', startDate: '', endDate: '', dateNotes: '', time: '', timeFrom: '', timeTo: '', location: '', channel: 'Bloom App', bookingLink: '', whatsappContact: '', offer: '', dialect: 'Kuwaiti', tone: 'Friendly & Casual', audience: 'Neutral', coveragePoints: '', content: {}, updatedAt: '' }

function formatDates(c) { if (c.dateNotes?.trim()) return c.dateNotes.trim(); if (!c.startDate) return ''; return c.endDate ? `${c.startDate} إلى ${c.endDate}` : c.startDate }
async function generateWithAI(form, kind) { const r = await fetch('/api/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ campaign: form, kind }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'Generation failed.'); return data.copy }

function App() {
  const [view, setView] = useState('new')
  const [form, setForm] = useState(emptyForm)
  const [campaigns, setCampaigns] = useState(() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]') } catch { return [] } })
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(null)
  const [error, setError] = useState('')
  const [editing, setEditing] = useState(null)
  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify(campaigns)), [campaigns])
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return q ? campaigns.filter(c => [c.name, c.brand, c.dialect, c.tone].some(v => String(v || '').toLowerCase().includes(q))) : campaigns }, [campaigns, search])
  const setField = (key, value) => setForm(p => ({ ...p, [key]: value }))
  const setContent = (key, value) => setForm(p => ({ ...p, content: { ...p.content, [key]: value } }))
  const generate = async kind => { setError(''); setLoading(kind); try { setContent(kind, await generateWithAI(form, kind)) } catch (e) { setError(e.message) } finally { setLoading(null) } }
  const generateAll = async () => { setError(''); setLoading('all'); try { const values = await Promise.all(COPY_TYPES.map(([kind]) => generateWithAI(form, kind))); setForm(p => ({ ...p, content: Object.fromEntries(COPY_TYPES.map(([kind], i) => [kind, values[i]])) })) } catch (e) { setError(e.message) } finally { setLoading(null) } }
  const save = () => { const saved = { ...form, id: form.id || Date.now(), updatedAt: new Date().toISOString() }; setCampaigns(p => p.some(c => c.id === saved.id) ? p.map(c => c.id === saved.id ? saved : c) : [saved, ...p]); setForm(saved) }
  const newCampaign = () => { setForm(emptyForm); setEditing(null); setError(''); setView('new') }
  const openCampaign = c => { setForm({ ...emptyForm, ...c, content: c.content || {} }); setEditing(null); setError(''); setView('new') }
  const locationType = LOCATION_TYPES.includes(form.type)

  return <div className="app-shell">
    <aside className="sidebar"><div className="echo-logo"><span>echo</span><b>OOO</b></div><div className="product-name"><span>Copy Writer</span><small>by Echo</small></div><nav><button className={view === 'new' ? 'active' : ''} onClick={newCampaign}><span>＋</span> New Campaign</button><button className={view === 'history' ? 'active' : ''} onClick={() => setView('history')}><span>▣</span> Campaign History</button></nav><div className="sidebar-footer"><span>AI COPY WORKSPACE</span><p>Copy Writer by Echo</p></div></aside>
    <main>{view === 'history' ? <History campaigns={filtered} search={search} setSearch={setSearch} onOpen={openCampaign} onDelete={id => setCampaigns(p => p.filter(c => c.id !== id))} onNew={newCampaign} /> : <>
      <header><div><p className="eyebrow">COPY WRITER BY ECHO · AI</p><h1>{form.id ? 'Edit Campaign' : 'New Campaign'}</h1><p className="subtle">Your campaign data goes through the Echo Copywriting Skill before the AI writes anything.</p></div><button className="primary" onClick={save}>Save Campaign</button></header>
      {error && <div className="panel" style={{ borderColor: '#e4b2aa', color: '#8d4035' }}><strong>AI error:</strong> {error}</div>}
      <section className="panel"><Section number="01" title="Campaign details" subtitle="Campaign name is internal only. It is never sent to the AI or shown to influencers." /><div className="form-grid"><Field label="Campaign Name (Internal)" required value={form.name} onChange={v => setField('name', v)} placeholder="e.g. Summer Cafe Visit — Aug" /><Field label="Brand Name" required value={form.brand} onChange={v => setField('brand', v)} placeholder="Brand name" /><Select label="Campaign Type" value={form.type} onChange={v => setField('type', v)} options={['Delivery', 'Visit', 'Event', 'Store Visit', 'Other']} /><Field label="Start Date" type="date" value={form.startDate} onChange={v => setField('startDate', v)} /><Field label="End Date" type="date" value={form.endDate} onChange={v => setField('endDate', v)} /><Field label="Additional / Multiple Dates" value={form.dateNotes} onChange={v => setField('dateNotes', v)} placeholder="e.g. Aug 20, 22 & 24" />{locationType && <Field className="full" label="Location / Branches" required value={form.location} onChange={v => setField('location', v)} placeholder="e.g. The Avenues / 360 Mall" hint="Use commas, /, or new lines for multiple branches." />}{locationType ? <><Field label="Available From" required type="time" value={form.timeFrom} onChange={v => setField('timeFrom', v)} /><Field label="Available To" required type="time" value={form.timeTo} onChange={v => setField('timeTo', v)} /></> : <Field label="Time" type="time" value={form.time} onChange={v => setField('time', v)} />}</div></section>
      <section className="panel"><Section number="02" title="Registration & offer" subtitle="The AI chooses the correct CTA based on the registration method and what actually needs confirmation." /><div className="form-grid"><Select label="Registration Method" value={form.channel} onChange={v => setField('channel', v)} options={['Bloom App', 'Booking Link', 'WhatsApp']} />{form.channel === 'Booking Link' && <Field label="Booking Link" type="url" value={form.bookingLink} onChange={v => setField('bookingLink', v)} placeholder="https://..." />}{form.channel === 'WhatsApp' && <Field label="WhatsApp Contact" value={form.whatsappContact} onChange={v => setField('whatsappContact', v)} placeholder="+965 ..." />}<label className="field full"><span>Gift / Offer</span><textarea rows="4" value={form.offer} onChange={e => setField('offer', e.target.value)} placeholder="Enter only confirmed gift, offer or experience details..." /></label></div></section>
      <section className="panel"><Section number="03" title="Copy direction" subtitle="Dialect changes the actual language. Tone changes the feel. Audience never defaults to a gender." /><div className="form-grid"><Select label="Dialect" value={form.dialect} onChange={v => setField('dialect', v)} options={DIALECTS} /><Select label="Invitation Tone" value={form.tone} onChange={v => setField('tone', v)} options={TONES} /><Select label="Influencer Audience" value={form.audience} onChange={v => setField('audience', v)} options={AUDIENCES} /><label className="field full"><span>Main Coverage Points <b>*</b></span><textarea rows="7" value={form.coveragePoints} onChange={e => setField('coveragePoints', e.target.value)} placeholder={'Write the main things you want the influencer to focus on.\nExample:\nHighlight the new drinks\nShow the outdoor seating\nMention the launch offer'} /><small className="field-hint">These are strategic inputs. The AI must add execution ideas instead of copying them into the brief.</small></label></div></section>
      <section className="content-head"><div><p className="eyebrow">ECHO COPYWRITING SKILL</p><h2>Campaign copy</h2><p className="subtle">AI-generated with separate rules for invitation, brief, reminder and notification.</p></div><div className="generator-actions">{COPY_TYPES.map(([key, label]) => <button key={key} onClick={() => generate(key)} disabled={!!loading}>{loading === key ? 'Writing…' : label}</button>)}<button className="primary" onClick={generateAll} disabled={!!loading}>{loading === 'all' ? 'Writing All…' : 'Generate All'}</button></div></section>
      <section className="content-grid">{COPY_TYPES.map(([key, label]) => <ContentCard key={key} title={label} text={form.content[key] || ''} editing={editing === key} onEdit={() => setEditing(editing === key ? null : key)} onChange={v => setContent(key, v)} onCopy={() => navigator.clipboard.writeText(form.content[key] || '')} onRegenerate={() => generate(key)} />)}</section>
    </>}</main>
  </div>
}

function Section({ number, title, subtitle }) { return <div className="section-title"><div><span className="section-number">{number}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div></div> }
function Field({ label, required, type = 'text', value, onChange, placeholder, hint, className = '' }) { return <label className={`field ${className}`}><span>{label}{required && <b> *</b>}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} required={required} />{hint && <small className="field-hint">{hint}</small>}</label> }
function Select({ label, value, onChange, options }) { return <label className="field"><span>{label}</span><select value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o}>{o}</option>)}</select></label> }
function ContentCard({ title, text, editing, onEdit, onChange, onCopy, onRegenerate }) { return <article className="copy-card"><div className="card-head"><h3>{title}</h3><span className={text ? 'ready' : 'draft'}>{text ? 'Ready' : 'Draft'}</span></div>{editing ? <textarea className="copy-editor" dir="rtl" value={text} onChange={e => onChange(e.target.value)} rows="12" /> : <p className={text ? 'arabic-copy' : 'placeholder'} dir={text ? 'rtl' : 'ltr'}>{text || 'Generate copy to preview it here.'}</p>}<div className="card-actions"><button onClick={onEdit} disabled={!text}>{editing ? 'Done' : 'Edit'}</button><button onClick={onCopy} disabled={!text}>Copy</button><button onClick={onRegenerate} disabled={!!editing}>Regenerate</button></div></article> }
function History({ campaigns, search, setSearch, onOpen, onDelete, onNew }) { return <><header><div><p className="eyebrow">COPY WRITER BY ECHO</p><h1>Campaign History</h1><p className="subtle">Find, reopen, or remove saved campaigns.</p></div><button className="primary" onClick={onNew}>New Campaign</button></header><section className="panel"><div className="history-tools"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search campaigns, brands, dialects..." /><span>{campaigns.length} saved</span></div>{campaigns.length ? <div className="campaign-list">{campaigns.map(c => <article className="campaign-row" key={c.id}><div><h3>{c.name}</h3><p>{c.brand}</p></div><div><small>DATES</small><p>{formatDates(c) || '—'}</p></div><div><small>STYLE</small><p>{c.dialect} · {c.tone}</p></div><div className="row-actions"><button onClick={() => onOpen(c)}>Open Campaign</button><button className="danger" onClick={() => onDelete(c.id)}>Delete</button></div></article>)}</div> : <div className="empty"><div>◇</div><h3>No campaigns found</h3><p>Create your first campaign to save it here.</p></div>}</section></> }
export default App
